branches:
  only:
  - master

services:
- mongodb

nuget:
  account_feed: true
  project_feed: true

init:
- git config --global core.autocrlf false

before_build:
- appveyor-retry dotnet restore -v Minimal
- choco install opencover.portable

environment:
 matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
 sonarCubeToken:
    secure: OTWdgq2KweeZ2YcYxhdERo1ePfAAnA7OXT1WwpeMdFD4NF0EjlmCaB3VZuvFe/QK

build_script:
- dotnet build
- dotnet test

test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -output:"coverage.xml" -oldstyle
- choco install "msbuild-sonarqube-runner" -y
- SonarScanner.MSBuild.exe begin /k:"Lauchi_Microwave" /v:%APPVEYOR_BUILD_VERSION% /d:sonar.organization="lauchi-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="%CD%\coverage.xml" /d:sonar.login=%sonarCubeToken%
- MsBuild.exe /t:Rebuild
- SonarScanner.MSBuild.exe end /d:sonar.login=%sonarCubeToken%